### PR TITLE
Use resolve package to resolve the path to the module more robustly.

### PR DESCRIPTION
**Pull request by aredridel**

### CODE REVIEW

**Comment by jasisk** [comment]
Looks good to me. What about a test?

**Comment by aredridel** [comment]
Test added!

**Comment by totherik** [comment]
Love it! Thank you!

**Comment by aredridel** [comment]
You're welcome!

**Comment by aredridel** [comment]
Time for a 1.0.1?

**Comment by totherik** [comment]
yerp. momentarily.

**Comment by totherik** [comment]
published.

**Pull request merged**
